### ISSUE TITLE
Raises error if house number is non-numeric

### ISSUE THREAD

**Issue by mvz** [rhomeister/api_postcode_nl#1]
Sometimes, a user may accidentally enter a non-numeric house number. If there is no `house_number_addition`, this causes an error in `ApiPostcodeNl::API.address`, line 71:

`TypeError: wrong argument type nil (expected Regexp)`.

**Comment by rhomeister** [comment]
Hi mvz,

Feel free to submit a PR for this. This gem is not actively maintained anymore, but I'd appreciate any and all contributions.

Cheers,
Ruben

**Comment by mvz** [comment]
Fixed in #2.
